language: node_js
node_js: stable

# S: Build Lifecycle
before_install:
  - wget https://imeoer.github.io/release/ink_linux_386.tar.gz
  - tar -zxvf ink_linux_386.tar.gz
  - ls
  - sudo mv ./ink /usr/local/bin/
 

script:
  - ink build

after_script:
  - git config user.name "w568w"
  - git config user.email "1278297578@qq.com"
  - rm -rf ink_linux_386.tar.gz
  - rm -rf ink_linux_386.tar.gz.1
  - rm -rf ink_linux_386.tar.gz.2
  - rm -rf ./blog/
  - rm -rf ./ink
  - git add .
  - git commit -m "Update"
  - if [ $(git log -1 | grep -c "Update") -gt 1 ]; then echo "true";else git push "https://${ttoken}@${GH_REF}" HEAD:master;fi
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/w568w/w568w.github.io.git